development:
  secret_key_base: here_goes_my_secret_key_base
  google_client_id: 581820041444-0jecs5n0fnl22401i49igdp5qch0171b.apps.googleusercontent.com
  google_client_secret: MOVdE7TV3vAB2GCkcLncGdRw

test:
  secret_key_base: here_goes_my_secret_key_base

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
