Category.find_or_create_by(name:"失礼度100%(親友)(Bạn thân)")
Category.find_or_create_by(name:"失礼度70%(友人)(Bạn bè)")
Category.find_or_create_by(name:"失礼度40%(同級生)(Bạn cùng lớp)")
Category.find_or_create_by(name:"失礼度10%(仲のいい先輩)(Đẹp cao cấp)")
Category.find_or_create_by(name:"失礼度0%(誰でも)(tất cả mọi người)")
Category.find_or_create_by(name:"その他：Khác")
