Category.find_or_create_by(name:"失礼度100%(親友)")
Category.find_or_create_by(name:"失礼度70%(友人)")
Category.find_or_create_by(name:"失礼度40%(同級生)")
Category.find_or_create_by(name:"失礼度10%(仲のいい先輩)")
Category.find_or_create_by(name:"失礼度0%(誰でも)")
Category.find_or_create_by(name:"その他")
Category.find_or_create_by(name:"質問 Câu hỏi")
